# Generated by Django 4.0.2 on 2022-02-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineDriveDetails',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=100)),
                ('vaccineName', models.CharField(max_length=100)),
                ('eventDate', models.DateField()),
                ('eventPlace', models.CharField(max_length=100)),
                ('maxSlots', models.IntegerField()),
                ('bookedSlots', models.IntegerField()),
            ],
        ),
    ]
