# Generated by Django 4.0.2 on 2022-02-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=100)),
                ('studentClass', models.IntegerField()),
                ('studentContact', models.BigIntegerField()),
                ('studentGender', models.CharField(max_length=1)),
                ('studentDOB', models.DateField()),
            ],
        ),
    ]
